require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DirecsController do

  # This should return the minimal set of attributes required to create a valid
  # Direc. As you add validations to Direc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DirecsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all direcs as @direcs" do
      direc = Direc.create! valid_attributes
      get :index, {}, valid_session
      assigns(:direcs).should eq([direc])
    end
  end

  describe "GET show" do
    it "assigns the requested direc as @direc" do
      direc = Direc.create! valid_attributes
      get :show, {:id => direc.to_param}, valid_session
      assigns(:direc).should eq(direc)
    end
  end

  describe "GET new" do
    it "assigns a new direc as @direc" do
      get :new, {}, valid_session
      assigns(:direc).should be_a_new(Direc)
    end
  end

  describe "GET edit" do
    it "assigns the requested direc as @direc" do
      direc = Direc.create! valid_attributes
      get :edit, {:id => direc.to_param}, valid_session
      assigns(:direc).should eq(direc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Direc" do
        expect {
          post :create, {:direc => valid_attributes}, valid_session
        }.to change(Direc, :count).by(1)
      end

      it "assigns a newly created direc as @direc" do
        post :create, {:direc => valid_attributes}, valid_session
        assigns(:direc).should be_a(Direc)
        assigns(:direc).should be_persisted
      end

      it "redirects to the created direc" do
        post :create, {:direc => valid_attributes}, valid_session
        response.should redirect_to(Direc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved direc as @direc" do
        # Trigger the behavior that occurs when invalid params are submitted
        Direc.any_instance.stub(:save).and_return(false)
        post :create, {:direc => { "nome" => "invalid value" }}, valid_session
        assigns(:direc).should be_a_new(Direc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Direc.any_instance.stub(:save).and_return(false)
        post :create, {:direc => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested direc" do
        direc = Direc.create! valid_attributes
        # Assuming there are no other direcs in the database, this
        # specifies that the Direc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Direc.any_instance.should_receive(:update).with({ "nome" => "MyString" })
        put :update, {:id => direc.to_param, :direc => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested direc as @direc" do
        direc = Direc.create! valid_attributes
        put :update, {:id => direc.to_param, :direc => valid_attributes}, valid_session
        assigns(:direc).should eq(direc)
      end

      it "redirects to the direc" do
        direc = Direc.create! valid_attributes
        put :update, {:id => direc.to_param, :direc => valid_attributes}, valid_session
        response.should redirect_to(direc)
      end
    end

    describe "with invalid params" do
      it "assigns the direc as @direc" do
        direc = Direc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Direc.any_instance.stub(:save).and_return(false)
        put :update, {:id => direc.to_param, :direc => { "nome" => "invalid value" }}, valid_session
        assigns(:direc).should eq(direc)
      end

      it "re-renders the 'edit' template" do
        direc = Direc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Direc.any_instance.stub(:save).and_return(false)
        put :update, {:id => direc.to_param, :direc => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested direc" do
      direc = Direc.create! valid_attributes
      expect {
        delete :destroy, {:id => direc.to_param}, valid_session
      }.to change(Direc, :count).by(-1)
    end

    it "redirects to the direcs list" do
      direc = Direc.create! valid_attributes
      delete :destroy, {:id => direc.to_param}, valid_session
      response.should redirect_to(direcs_url)
    end
  end

end
