require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EncarregadosController do

  # This should return the minimal set of attributes required to create a valid
  # Encarregado. As you add validations to Encarregado, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EncarregadosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all encarregados as @encarregados" do
      encarregado = Encarregado.create! valid_attributes
      get :index, {}, valid_session
      assigns(:encarregados).should eq([encarregado])
    end
  end

  describe "GET show" do
    it "assigns the requested encarregado as @encarregado" do
      encarregado = Encarregado.create! valid_attributes
      get :show, {:id => encarregado.to_param}, valid_session
      assigns(:encarregado).should eq(encarregado)
    end
  end

  describe "GET new" do
    it "assigns a new encarregado as @encarregado" do
      get :new, {}, valid_session
      assigns(:encarregado).should be_a_new(Encarregado)
    end
  end

  describe "GET edit" do
    it "assigns the requested encarregado as @encarregado" do
      encarregado = Encarregado.create! valid_attributes
      get :edit, {:id => encarregado.to_param}, valid_session
      assigns(:encarregado).should eq(encarregado)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Encarregado" do
        expect {
          post :create, {:encarregado => valid_attributes}, valid_session
        }.to change(Encarregado, :count).by(1)
      end

      it "assigns a newly created encarregado as @encarregado" do
        post :create, {:encarregado => valid_attributes}, valid_session
        assigns(:encarregado).should be_a(Encarregado)
        assigns(:encarregado).should be_persisted
      end

      it "redirects to the created encarregado" do
        post :create, {:encarregado => valid_attributes}, valid_session
        response.should redirect_to(Encarregado.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved encarregado as @encarregado" do
        # Trigger the behavior that occurs when invalid params are submitted
        Encarregado.any_instance.stub(:save).and_return(false)
        post :create, {:encarregado => { "nome" => "invalid value" }}, valid_session
        assigns(:encarregado).should be_a_new(Encarregado)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Encarregado.any_instance.stub(:save).and_return(false)
        post :create, {:encarregado => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested encarregado" do
        encarregado = Encarregado.create! valid_attributes
        # Assuming there are no other encarregados in the database, this
        # specifies that the Encarregado created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Encarregado.any_instance.should_receive(:update).with({ "nome" => "MyString" })
        put :update, {:id => encarregado.to_param, :encarregado => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested encarregado as @encarregado" do
        encarregado = Encarregado.create! valid_attributes
        put :update, {:id => encarregado.to_param, :encarregado => valid_attributes}, valid_session
        assigns(:encarregado).should eq(encarregado)
      end

      it "redirects to the encarregado" do
        encarregado = Encarregado.create! valid_attributes
        put :update, {:id => encarregado.to_param, :encarregado => valid_attributes}, valid_session
        response.should redirect_to(encarregado)
      end
    end

    describe "with invalid params" do
      it "assigns the encarregado as @encarregado" do
        encarregado = Encarregado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Encarregado.any_instance.stub(:save).and_return(false)
        put :update, {:id => encarregado.to_param, :encarregado => { "nome" => "invalid value" }}, valid_session
        assigns(:encarregado).should eq(encarregado)
      end

      it "re-renders the 'edit' template" do
        encarregado = Encarregado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Encarregado.any_instance.stub(:save).and_return(false)
        put :update, {:id => encarregado.to_param, :encarregado => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested encarregado" do
      encarregado = Encarregado.create! valid_attributes
      expect {
        delete :destroy, {:id => encarregado.to_param}, valid_session
      }.to change(Encarregado, :count).by(-1)
    end

    it "redirects to the encarregados list" do
      encarregado = Encarregado.create! valid_attributes
      delete :destroy, {:id => encarregado.to_param}, valid_session
      response.should redirect_to(encarregados_url)
    end
  end

end
