require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NotaController do

  # This should return the minimal set of attributes required to create a valid
  # Notum. As you add validations to Notum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "valor" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NotaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all nota as @nota" do
      notum = Notum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:nota).should eq([notum])
    end
  end

  describe "GET show" do
    it "assigns the requested notum as @notum" do
      notum = Notum.create! valid_attributes
      get :show, {:id => notum.to_param}, valid_session
      assigns(:notum).should eq(notum)
    end
  end

  describe "GET new" do
    it "assigns a new notum as @notum" do
      get :new, {}, valid_session
      assigns(:notum).should be_a_new(Notum)
    end
  end

  describe "GET edit" do
    it "assigns the requested notum as @notum" do
      notum = Notum.create! valid_attributes
      get :edit, {:id => notum.to_param}, valid_session
      assigns(:notum).should eq(notum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Notum" do
        expect {
          post :create, {:notum => valid_attributes}, valid_session
        }.to change(Notum, :count).by(1)
      end

      it "assigns a newly created notum as @notum" do
        post :create, {:notum => valid_attributes}, valid_session
        assigns(:notum).should be_a(Notum)
        assigns(:notum).should be_persisted
      end

      it "redirects to the created notum" do
        post :create, {:notum => valid_attributes}, valid_session
        response.should redirect_to(Notum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved notum as @notum" do
        # Trigger the behavior that occurs when invalid params are submitted
        Notum.any_instance.stub(:save).and_return(false)
        post :create, {:notum => { "valor" => "invalid value" }}, valid_session
        assigns(:notum).should be_a_new(Notum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Notum.any_instance.stub(:save).and_return(false)
        post :create, {:notum => { "valor" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested notum" do
        notum = Notum.create! valid_attributes
        # Assuming there are no other nota in the database, this
        # specifies that the Notum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Notum.any_instance.should_receive(:update).with({ "valor" => "MyString" })
        put :update, {:id => notum.to_param, :notum => { "valor" => "MyString" }}, valid_session
      end

      it "assigns the requested notum as @notum" do
        notum = Notum.create! valid_attributes
        put :update, {:id => notum.to_param, :notum => valid_attributes}, valid_session
        assigns(:notum).should eq(notum)
      end

      it "redirects to the notum" do
        notum = Notum.create! valid_attributes
        put :update, {:id => notum.to_param, :notum => valid_attributes}, valid_session
        response.should redirect_to(notum)
      end
    end

    describe "with invalid params" do
      it "assigns the notum as @notum" do
        notum = Notum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Notum.any_instance.stub(:save).and_return(false)
        put :update, {:id => notum.to_param, :notum => { "valor" => "invalid value" }}, valid_session
        assigns(:notum).should eq(notum)
      end

      it "re-renders the 'edit' template" do
        notum = Notum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Notum.any_instance.stub(:save).and_return(false)
        put :update, {:id => notum.to_param, :notum => { "valor" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested notum" do
      notum = Notum.create! valid_attributes
      expect {
        delete :destroy, {:id => notum.to_param}, valid_session
      }.to change(Notum, :count).by(-1)
    end

    it "redirects to the nota list" do
      notum = Notum.create! valid_attributes
      delete :destroy, {:id => notum.to_param}, valid_session
      response.should redirect_to(nota_url)
    end
  end

end
