require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProfsController do

  # This should return the minimal set of attributes required to create a valid
  # Prof. As you add validations to Prof, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nome" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProfsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all profs as @profs" do
      prof = Prof.create! valid_attributes
      get :index, {}, valid_session
      assigns(:profs).should eq([prof])
    end
  end

  describe "GET show" do
    it "assigns the requested prof as @prof" do
      prof = Prof.create! valid_attributes
      get :show, {:id => prof.to_param}, valid_session
      assigns(:prof).should eq(prof)
    end
  end

  describe "GET new" do
    it "assigns a new prof as @prof" do
      get :new, {}, valid_session
      assigns(:prof).should be_a_new(Prof)
    end
  end

  describe "GET edit" do
    it "assigns the requested prof as @prof" do
      prof = Prof.create! valid_attributes
      get :edit, {:id => prof.to_param}, valid_session
      assigns(:prof).should eq(prof)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Prof" do
        expect {
          post :create, {:prof => valid_attributes}, valid_session
        }.to change(Prof, :count).by(1)
      end

      it "assigns a newly created prof as @prof" do
        post :create, {:prof => valid_attributes}, valid_session
        assigns(:prof).should be_a(Prof)
        assigns(:prof).should be_persisted
      end

      it "redirects to the created prof" do
        post :create, {:prof => valid_attributes}, valid_session
        response.should redirect_to(Prof.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prof as @prof" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prof.any_instance.stub(:save).and_return(false)
        post :create, {:prof => { "nome" => "invalid value" }}, valid_session
        assigns(:prof).should be_a_new(Prof)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Prof.any_instance.stub(:save).and_return(false)
        post :create, {:prof => { "nome" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prof" do
        prof = Prof.create! valid_attributes
        # Assuming there are no other profs in the database, this
        # specifies that the Prof created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Prof.any_instance.should_receive(:update).with({ "nome" => "MyString" })
        put :update, {:id => prof.to_param, :prof => { "nome" => "MyString" }}, valid_session
      end

      it "assigns the requested prof as @prof" do
        prof = Prof.create! valid_attributes
        put :update, {:id => prof.to_param, :prof => valid_attributes}, valid_session
        assigns(:prof).should eq(prof)
      end

      it "redirects to the prof" do
        prof = Prof.create! valid_attributes
        put :update, {:id => prof.to_param, :prof => valid_attributes}, valid_session
        response.should redirect_to(prof)
      end
    end

    describe "with invalid params" do
      it "assigns the prof as @prof" do
        prof = Prof.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prof.any_instance.stub(:save).and_return(false)
        put :update, {:id => prof.to_param, :prof => { "nome" => "invalid value" }}, valid_session
        assigns(:prof).should eq(prof)
      end

      it "re-renders the 'edit' template" do
        prof = Prof.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Prof.any_instance.stub(:save).and_return(false)
        put :update, {:id => prof.to_param, :prof => { "nome" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prof" do
      prof = Prof.create! valid_attributes
      expect {
        delete :destroy, {:id => prof.to_param}, valid_session
      }.to change(Prof, :count).by(-1)
    end

    it "redirects to the profs list" do
      prof = Prof.create! valid_attributes
      delete :destroy, {:id => prof.to_param}, valid_session
      response.should redirect_to(profs_url)
    end
  end

end
